### ISSUE TITLE
[BUG] Firefox 115.0.2 - connection is shown as insecure for every websites

### ISSUE THREAD

**Issue by Tutul-** [Internet-Society-Belgium/isTrust#129]
For a while now, the addons seem to be unable to access HTTPS status and mark all connection as insecure without any details.
But as I can show you, even here on github, the connection is well secured.

I must add that I use Firefox in strict mode (if that may impact your api)

![image](https://github.com/Internet-Society-Belgium/isTrust/assets/4596884/be4cc7a4-55ae-4b59-9ee4-32745c5dca62)
![image](https://github.com/Internet-Society-Belgium/isTrust/assets/4596884/c4f3a000-a0b9-4de7-8250-aab397c81c4f)

**Comment by etoome** [comment]
Thank you for opening an issue. The problem has been fixed. The HTTPS infos should be available after the DNS propagation.
