### ISSUE TITLE
eval : security issue

### ISSUE THREAD

**Issue by tsf007** [Internet-Society-Belgium/isTrust#63]
When publishing the extension on Mozilla, an automated check informed it could be refused because of following issue:

The Function constructor is eval.

Warning: Evaluation of strings as code can lead to security vulnerabilities and performance issues, even in the most innocuous of circumstances. Please avoid using `eval` and the `Function` constructor when at all possible.'
popup/index.js line 2 column 2766896

**Comment by Progitiel** [comment]
https://github.com/zloirock/core-js/issues/86#issuecomment-115759028
