### ISSUE TITLE
Unsafe assignment to innerHTML

### ISSUE THREAD

**Issue by tsf007** [Internet-Society-Belgium/isTrust#64]
When publishing the extension on Mozilla, an automated check informed it could be refused because of the following issue:

Unsafe assignment to innerHTML

Warning: Due to both security and performance concerns, this may not be set using dynamic values which have not been adequately sanitized. This can lead to security issues or fairly serious performance degradation.
popup/index.js line 2 column 2811011

**Comment by Progitiel** [comment]
"As long as the user only uses trusted templates, this is safe"
